// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import jsoniter "github.com/json-iterator/go"

const TableNameConfig = "config"

// Config 配置
type Config struct {
	ID     uint32  `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name   string  `gorm:"column:name;type:varchar(30);not null;comment:名称" json:"name"`     // 名称
	Group_ string  `gorm:"column:group;type:varchar(30);not null;comment:分组" json:"group"`   // 分组
	Title  string  `gorm:"column:title;type:varchar(50);not null;comment:变量标题" json:"title"` // 变量标题
	Type   string  `gorm:"column:type;type:varchar(30);not null;comment:数据类型" json:"type"`   // 数据类型
	Value  *string `gorm:"column:value;type:longtext;comment:变量值" json:"value"`              // 变量值
}

// MarshalBinary 支持json序列化
func (m *Config) MarshalBinary() (data []byte, err error) {
	return jsoniter.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *Config) UnmarshalBinary(data []byte) error {
	return jsoniter.Unmarshal(data, m)
}

// TableName Config's table name
func (*Config) TableName() string {
	return TableNameConfig
}
