// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import jsoniter "github.com/json-iterator/go"

const TableNameConfig = "config"

// Config mapped from table <config>
type Config struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name   string `gorm:"column:name;not null;comment:名称" json:"name"`     // 名称
	Group_ string `gorm:"column:group;not null;comment:分组" json:"group"`   // 分组
	Title  string `gorm:"column:title;not null;comment:变量标题" json:"title"` // 变量标题
	Type   string `gorm:"column:type;not null;comment:数据类型" json:"type"`   // 数据类型
	Value  string `gorm:"column:value;comment:变量值" json:"value"`           // 变量值
}

// MarshalBinary 支持json序列化
func (m *Config) MarshalBinary() (data []byte, err error) {
	return jsoniter.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *Config) UnmarshalBinary(data []byte) error {
	return jsoniter.Unmarshal(data, m)
}

// TableName Config's table name
func (*Config) TableName() string {
	return TableNameConfig
}
