// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import jsoniter "github.com/json-iterator/go"

const TableNameFileMenu = "file_menu"

// FileMenu 文件分组
type FileMenu struct {
	ID   uint32 `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;type:varchar(255);not null;comment:名称" json:"name"` // 名称
}

// MarshalBinary 支持json序列化
func (m *FileMenu) MarshalBinary() (data []byte, err error) {
	return jsoniter.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *FileMenu) UnmarshalBinary(data []byte) error {
	return jsoniter.Unmarshal(data, m)
}

// TableName FileMenu's table name
func (*FileMenu) TableName() string {
	return TableNameFileMenu
}
