// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	jsoniter "github.com/json-iterator/go"
	"gorm.io/gorm"
)

const TableNameFile = "file"

// File 文件
type File struct {
	ID         uint32         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	FileName   string         `gorm:"column:file_name;type:varchar(255);not null;comment:文件名" json:"file_name"`                     // 文件名
	FileType   string         `gorm:"column:file_type;type:varchar(50);not null;comment:文件类型（MIME类型，如 image/png）" json:"file_type"` // 文件类型（MIME类型，如 image/png）
	FileExt    string         `gorm:"column:file_ext;type:varchar(20);not null;comment:文件后缀（如 .jpg/.pdf）文件后缀" json:"file_ext"`      // 文件后缀（如 .jpg/.pdf）文件后缀
	FileSize   int64          `gorm:"column:file_size;type:bigint;not null;comment:文件大小（字节）" json:"file_size"`                      // 文件大小（字节）
	URL        string         `gorm:"column:url;type:varchar(255);not null;comment:链接地址" json:"url"`                                // 链接地址
	FilePath   string         `gorm:"column:file_path;type:varchar(1024);not null;comment:存储路径" json:"file_path"`                   // 存储路径
	MenuID     uint32         `gorm:"column:menu_id;type:int unsigned;not null" json:"menu_id"`
	StorageID  uint32         `gorm:"column:storage_id;type:int unsigned;not null;comment:存储方式id" json:"storage_id"`          // 存储方式id
	StorageKey string         `gorm:"column:storage_key;type:varchar(20);not null;comment:储存方式key" json:"storage_key"`        // 储存方式key
	HashMd5    string         `gorm:"column:hash_md5;type:char(32);not null;comment:文件内容的MD5" json:"hash_md5"`                // 文件内容的MD5
	UserID     uint32         `gorm:"column:user_id;type:int unsigned;not null;comment:上传用户id" json:"user_id"`                // 上传用户id
	Status     int32          `gorm:"column:status;type:tinyint;not null;default:1;comment:状态 1=正常 0=停用" json:"status"`       // 状态 1=正常 0=停用
	CreatedAt  time.Time      `gorm:"column:created_at;type:datetime;not null;autoCreateTime;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at;type:datetime;not null;autoUpdateTime;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                         // 删除时间
}

// MarshalBinary 支持json序列化
func (m *File) MarshalBinary() (data []byte, err error) {
	return jsoniter.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *File) UnmarshalBinary(data []byte) error {
	return jsoniter.Unmarshal(data, m)
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
