// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"encoding/json"
)

const TableNameLogLevel = "log_level"

// LogLevel 日志级别
type LogLevel struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:<10为系统日志" json:"id"` // <10为系统日志
	Name   string `gorm:"column:name;not null;comment:中文名称" json:"name"`                      // 中文名称
	Label  string `gorm:"column:label;not null;comment:英文别名" json:"label"`                    // 英文别名
	Remark string `gorm:"column:remark;not null;comment:备注" json:"remark"`                    // 备注
	Status int32  `gorm:"column:status;not null;default:1;comment:日志开启状态" json:"status"`      // 日志开启状态
	Color  string `gorm:"column:color;not null;comment:日志颜色 #ff0000" json:"color"`            // 日志颜色 #ff0000
}

// MarshalBinary 支持json序列化
func (m *LogLevel) MarshalBinary() (data []byte, err error) {
	return json.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *LogLevel) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, m)
}

// TableName LogLevel's table name
func (*LogLevel) TableName() string {
	return TableNameLogLevel
}
