// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"encoding/json"
)

const TableNameLogStatView = "log_stat_view"

// LogStatView VIEW
type LogStatView struct {
	Date     string `gorm:"column:date" json:"date"`
	Count_   int64  `gorm:"column:count;not null" json:"count"`
	TypeName string `gorm:"column:type_name;not null;comment:日志级别名称" json:"type_name"`    // 日志级别名称
	TypeID   int32  `gorm:"column:type_id;not null;comment:日志级别 <10为系统日志" json:"type_id"` // 日志级别 <10为系统日志
}

// MarshalBinary 支持json序列化
func (m *LogStatView) MarshalBinary() (data []byte, err error) {
	return json.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *LogStatView) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, m)
}

// TableName LogStatView's table name
func (*LogStatView) TableName() string {
	return TableNameLogStatView
}
