// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"encoding/json"
)

const TableNameMenuAPI = "menu_api"

// MenuAPI 菜单权限接口
type MenuAPI struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AppID  int32  `gorm:"column:app_id;not null;comment:应用ID" json:"app_id"`   // 应用ID
	MenuID int32  `gorm:"column:menu_id;not null;comment:菜单ID" json:"menu_id"` // 菜单ID
	Path   string `gorm:"column:path;not null;comment:API路由地址" json:"path"`    // API路由地址
	Tag    string `gorm:"column:tag;not null;comment:标识" json:"tag"`           // 标识
}

// MarshalBinary 支持json序列化
func (m *MenuAPI) MarshalBinary() (data []byte, err error) {
	return json.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *MenuAPI) UnmarshalBinary(data []byte) error {
	return json.Unmarshal(data, m)
}

// TableName MenuAPI's table name
func (*MenuAPI) TableName() string {
	return TableNameMenuAPI
}
