// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import jsoniter "github.com/json-iterator/go"

const TableNameMenuAPI = "menu_api"

// MenuAPI 菜单权限接口
type MenuAPI struct {
	ID     uint32 `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	AppID  uint32 `gorm:"column:app_id;type:int unsigned;not null;comment:应用ID" json:"app_id"`   // 应用ID
	MenuID uint32 `gorm:"column:menu_id;type:int unsigned;not null;comment:菜单ID" json:"menu_id"` // 菜单ID
	Path   string `gorm:"column:path;type:varchar(255);not null;comment:API路由地址" json:"path"`    // API路由地址
	Tag    string `gorm:"column:tag;type:varchar(255);not null;comment:标识" json:"tag"`           // 标识
}

// MarshalBinary 支持json序列化
func (m *MenuAPI) MarshalBinary() (data []byte, err error) {
	return jsoniter.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *MenuAPI) UnmarshalBinary(data []byte) error {
	return jsoniter.Unmarshal(data, m)
}

// TableName MenuAPI's table name
func (*MenuAPI) TableName() string {
	return TableNameMenuAPI
}
