// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	jsoniter "github.com/json-iterator/go"
	"gorm.io/gorm"
)

const TableNameRole = "role"

// Role 用户角色
type Role struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AppID       int64          `gorm:"column:app_id;not null;comment:应用ID" json:"app_id"`                    // 应用ID
	Name        string         `gorm:"column:name;not null;comment:角色名称" json:"name"`                        // 角色名称
	Rules       string         `gorm:"column:rules;not null;comment:权限ID ,分割a" json:"rules"`                 // 权限ID ,分割a
	RulesCheckd string         `gorm:"column:rules_checkd;not null;comment:权限树选中的字节点ID" json:"rules_checkd"` // 权限树选中的字节点ID
	Remark      string         `gorm:"column:remark;not null;comment:简介" json:"remark"`                      // 简介
	Status      int32          `gorm:"column:status;not null;comment:状态" json:"status"`                      // 状态
	Sort        int32          `gorm:"column:sort;not null;comment:排序" json:"sort"`                          // 排序
	IsAdmin     int32          `gorm:"column:is_admin;not null;comment:是否为管理员（所有权限）" json:"is_admin"`        // 是否为管理员（所有权限）
	CreatedAt   time.Time      `gorm:"column:created_at;autoCreateTime;comment:创建时间" json:"created_at"`      // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;autoUpdateTime;comment:更新时间" json:"updated_at"`      // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                     // 删除时间
	App         App            `gorm:"foreignKey:app_id;references:id" json:"app"`
}

// MarshalBinary 支持json序列化
func (m *Role) MarshalBinary() (data []byte, err error) {
	return jsoniter.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *Role) UnmarshalBinary(data []byte) error {
	return jsoniter.Unmarshal(data, m)
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
