// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	jsoniter "github.com/json-iterator/go"
	"gorm.io/gorm"
)

const TableNameTask = "task"

// Task 任务
type Task struct {
	ID         int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title      string         `gorm:"column:title;not null;comment:任务标题" json:"title"`                          // 任务标题
	Group_     string         `gorm:"column:group;not null;default:system;comment:分组" json:"group"`             // 分组
	UserID     int64          `gorm:"column:user_id;not null;comment:关联用户ID" json:"user_id"`                    // 关联用户ID
	Type       string         `gorm:"column:type;not null;comment:任务类型" json:"type"`                            // 任务类型
	Content    string         `gorm:"column:content;not null;comment:任务内容" json:"content"`                      // 任务内容
	Status     int32          `gorm:"column:status;not null;comment:状态 0=待处理 1=处理中 2=已完成 -1=失败" json:"status"`  // 状态 0=待处理 1=处理中 2=已完成 -1=失败
	StatusName string         `gorm:"column:status_name;not null;comment:状态名称" json:"status_name"`              // 状态名称
	CreatedAt  time.Time      `gorm:"column:created_at;not null;autoCreateTime;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at;not null;autoUpdateTime;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                         // 删除时间
}

// MarshalBinary 支持json序列化
func (m *Task) MarshalBinary() (data []byte, err error) {
	return jsoniter.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *Task) UnmarshalBinary(data []byte) error {
	return jsoniter.Unmarshal(data, m)
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
