// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	jsoniter "github.com/json-iterator/go"
	"gorm.io/gorm"
)

const TableNameUser = "user"

// User 用户表
type User struct {
	ID        uint32         `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	Nickname  string         `gorm:"column:nickname;type:char(32);not null;comment:昵称" json:"nickname"`                      // 昵称
	Username  string         `gorm:"column:username;type:char(32);not null;comment:用户名(登录账号)" json:"username"`               // 用户名(登录账号)
	Avatar    string         `gorm:"column:avatar;type:varchar(255);not null;comment:头像" json:"avatar"`                      // 头像
	Password  string         `gorm:"column:password;type:char(32);not null;comment:密码 md5" json:"password"`                  // 密码 md5
	Status    int32          `gorm:"column:status;type:tinyint;not null;comment:状态" json:"status"`                           // 状态
	LoginTime *time.Time     `gorm:"column:login_time;type:datetime;comment:登录时间" json:"login_time"`                         // 登录时间
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;autoCreateTime;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;not null;autoUpdateTime;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                         // 删除时间
	UserRole  []UserRole     `gorm:"foreignKey:user_id;references:id" json:"user_role"`
}

// MarshalBinary 支持json序列化
func (m *User) MarshalBinary() (data []byte, err error) {
	return jsoniter.Marshal(m)
}

// UnmarshalBinary 支持json反序列化
func (m *User) UnmarshalBinary(data []byte) error {
	return jsoniter.Unmarshal(data, m)
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
