// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/orm/model"
)

func newFileMenu(db *gorm.DB, opts ...gen.DOOption) fileMenu {
	_fileMenu := fileMenu{}

	_fileMenu.fileMenuDo.UseDB(db, opts...)
	_fileMenu.fileMenuDo.UseModel(&model.FileMenu{})

	tableName := _fileMenu.fileMenuDo.TableName()
	_fileMenu.ALL = field.NewAsterisk(tableName)
	_fileMenu.ID = field.NewInt32(tableName, "id")
	_fileMenu.Name = field.NewString(tableName, "name")

	_fileMenu.fillFieldMap()

	return _fileMenu
}

// fileMenu 文件分组
type fileMenu struct {
	fileMenuDo

	ALL  field.Asterisk
	ID   field.Int32
	Name field.String // 名称

	fieldMap map[string]field.Expr
}

func (f fileMenu) Table(newTableName string) *fileMenu {
	f.fileMenuDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fileMenu) As(alias string) *fileMenu {
	f.fileMenuDo.DO = *(f.fileMenuDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fileMenu) updateTableName(table string) *fileMenu {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt32(table, "id")
	f.Name = field.NewString(table, "name")

	f.fillFieldMap()

	return f
}

func (f *fileMenu) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fileMenu) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 2)
	f.fieldMap["id"] = f.ID
	f.fieldMap["name"] = f.Name
}

func (f fileMenu) clone(db *gorm.DB) fileMenu {
	f.fileMenuDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fileMenu) replaceDB(db *gorm.DB) fileMenu {
	f.fileMenuDo.ReplaceDB(db)
	return f
}

type fileMenuDo struct{ gen.DO }

func (f fileMenuDo) Debug() *fileMenuDo {
	return f.withDO(f.DO.Debug())
}

func (f fileMenuDo) WithContext(ctx context.Context) *fileMenuDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fileMenuDo) ReadDB() *fileMenuDo {
	return f.Clauses(dbresolver.Read)
}

func (f fileMenuDo) WriteDB() *fileMenuDo {
	return f.Clauses(dbresolver.Write)
}

func (f fileMenuDo) Session(config *gorm.Session) *fileMenuDo {
	return f.withDO(f.DO.Session(config))
}

func (f fileMenuDo) Clauses(conds ...clause.Expression) *fileMenuDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fileMenuDo) Returning(value interface{}, columns ...string) *fileMenuDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fileMenuDo) Not(conds ...gen.Condition) *fileMenuDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fileMenuDo) Or(conds ...gen.Condition) *fileMenuDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fileMenuDo) Select(conds ...field.Expr) *fileMenuDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fileMenuDo) Where(conds ...gen.Condition) *fileMenuDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fileMenuDo) Order(conds ...field.Expr) *fileMenuDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fileMenuDo) Distinct(cols ...field.Expr) *fileMenuDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fileMenuDo) Omit(cols ...field.Expr) *fileMenuDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fileMenuDo) Join(table schema.Tabler, on ...field.Expr) *fileMenuDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fileMenuDo) LeftJoin(table schema.Tabler, on ...field.Expr) *fileMenuDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fileMenuDo) RightJoin(table schema.Tabler, on ...field.Expr) *fileMenuDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fileMenuDo) Group(cols ...field.Expr) *fileMenuDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fileMenuDo) Having(conds ...gen.Condition) *fileMenuDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fileMenuDo) Limit(limit int) *fileMenuDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fileMenuDo) Offset(offset int) *fileMenuDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fileMenuDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *fileMenuDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fileMenuDo) Unscoped() *fileMenuDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fileMenuDo) Create(values ...*model.FileMenu) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fileMenuDo) CreateInBatches(values []*model.FileMenu, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fileMenuDo) Save(values ...*model.FileMenu) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fileMenuDo) First() (*model.FileMenu, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FileMenu), nil
	}
}

func (f fileMenuDo) Take() (*model.FileMenu, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FileMenu), nil
	}
}

func (f fileMenuDo) Last() (*model.FileMenu, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FileMenu), nil
	}
}

func (f fileMenuDo) Find() ([]*model.FileMenu, error) {
	result, err := f.DO.Find()
	return result.([]*model.FileMenu), err
}

func (f fileMenuDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FileMenu, err error) {
	buf := make([]*model.FileMenu, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fileMenuDo) FindInBatches(result *[]*model.FileMenu, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fileMenuDo) Attrs(attrs ...field.AssignExpr) *fileMenuDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fileMenuDo) Assign(attrs ...field.AssignExpr) *fileMenuDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fileMenuDo) Joins(fields ...field.RelationField) *fileMenuDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fileMenuDo) Preload(fields ...field.RelationField) *fileMenuDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fileMenuDo) FirstOrInit() (*model.FileMenu, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FileMenu), nil
	}
}

func (f fileMenuDo) FirstOrCreate() (*model.FileMenu, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FileMenu), nil
	}
}

func (f fileMenuDo) FindByPage(offset int, limit int) (result []*model.FileMenu, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fileMenuDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fileMenuDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fileMenuDo) Delete(models ...*model.FileMenu) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fileMenuDo) withDO(do gen.Dao) *fileMenuDo {
	f.DO = *do.(*gen.DO)
	return f
}
