// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/orm/model"
)

func newLog(db *gorm.DB, opts ...gen.DOOption) log {
	_log := log{}

	_log.logDo.UseDB(db, opts...)
	_log.logDo.UseModel(&model.Log{})

	tableName := _log.logDo.TableName()
	_log.ALL = field.NewAsterisk(tableName)
	_log.ID = field.NewUint32(tableName, "id")
	_log.AppID = field.NewUint32(tableName, "app_id")
	_log.TypeID = field.NewUint32(tableName, "type_id")
	_log.TypeName = field.NewString(tableName, "type_name")
	_log.Title = field.NewString(tableName, "title")
	_log.Value = field.NewString(tableName, "value")
	_log.ValueType = field.NewString(tableName, "value_type")
	_log.RequestSource = field.NewString(tableName, "request_source")
	_log.RequestIP = field.NewString(tableName, "request_ip")
	_log.RequestUserID = field.NewUint32(tableName, "request_user_id")
	_log.RequestUser = field.NewString(tableName, "request_user")
	_log.Status = field.NewUint32(tableName, "status")
	_log.CreatedAt = field.NewTime(tableName, "created_at")
	_log.UpdatedAt = field.NewTime(tableName, "updated_at")
	_log.LogType = logHasOneLogType{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("LogType", "model.LogType"),
	}

	_log.fillFieldMap()

	return _log
}

// log 日志表
type log struct {
	logDo

	ALL           field.Asterisk
	ID            field.Uint32
	AppID         field.Uint32 // 应用ID 0为未知
	TypeID        field.Uint32 // 日志级别 <10为系统日志
	TypeName      field.String // 日志级别名称
	Title         field.String // 标题
	Value         field.String // 日志内容
	ValueType     field.String // 日志类型  text,json,html
	RequestSource field.String // 请求来源
	RequestIP     field.String // 请求来源IP
	RequestUserID field.Uint32 // 操作人ID
	RequestUser   field.String // 操作人
	Status        field.Uint32 // 状态 0=未处理 1=已查看 2=已处理
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间
	LogType       logHasOneLogType

	fieldMap map[string]field.Expr
}

func (l log) Table(newTableName string) *log {
	l.logDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l log) As(alias string) *log {
	l.logDo.DO = *(l.logDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *log) updateTableName(table string) *log {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewUint32(table, "id")
	l.AppID = field.NewUint32(table, "app_id")
	l.TypeID = field.NewUint32(table, "type_id")
	l.TypeName = field.NewString(table, "type_name")
	l.Title = field.NewString(table, "title")
	l.Value = field.NewString(table, "value")
	l.ValueType = field.NewString(table, "value_type")
	l.RequestSource = field.NewString(table, "request_source")
	l.RequestIP = field.NewString(table, "request_ip")
	l.RequestUserID = field.NewUint32(table, "request_user_id")
	l.RequestUser = field.NewString(table, "request_user")
	l.Status = field.NewUint32(table, "status")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")

	l.fillFieldMap()

	return l
}

func (l *log) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *log) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 15)
	l.fieldMap["id"] = l.ID
	l.fieldMap["app_id"] = l.AppID
	l.fieldMap["type_id"] = l.TypeID
	l.fieldMap["type_name"] = l.TypeName
	l.fieldMap["title"] = l.Title
	l.fieldMap["value"] = l.Value
	l.fieldMap["value_type"] = l.ValueType
	l.fieldMap["request_source"] = l.RequestSource
	l.fieldMap["request_ip"] = l.RequestIP
	l.fieldMap["request_user_id"] = l.RequestUserID
	l.fieldMap["request_user"] = l.RequestUser
	l.fieldMap["status"] = l.Status
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt

}

func (l log) clone(db *gorm.DB) log {
	l.logDo.ReplaceConnPool(db.Statement.ConnPool)
	l.LogType.db = db.Session(&gorm.Session{Initialized: true})
	l.LogType.db.Statement.ConnPool = db.Statement.ConnPool
	return l
}

func (l log) replaceDB(db *gorm.DB) log {
	l.logDo.ReplaceDB(db)
	l.LogType.db = db.Session(&gorm.Session{})
	return l
}

type logHasOneLogType struct {
	db *gorm.DB

	field.RelationField
}

func (a logHasOneLogType) Where(conds ...field.Expr) *logHasOneLogType {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a logHasOneLogType) WithContext(ctx context.Context) *logHasOneLogType {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a logHasOneLogType) Session(session *gorm.Session) *logHasOneLogType {
	a.db = a.db.Session(session)
	return &a
}

func (a logHasOneLogType) Model(m *model.Log) *logHasOneLogTypeTx {
	return &logHasOneLogTypeTx{a.db.Model(m).Association(a.Name())}
}

func (a logHasOneLogType) Unscoped() *logHasOneLogType {
	a.db = a.db.Unscoped()
	return &a
}

type logHasOneLogTypeTx struct{ tx *gorm.Association }

func (a logHasOneLogTypeTx) Find() (result *model.LogType, err error) {
	return result, a.tx.Find(&result)
}

func (a logHasOneLogTypeTx) Append(values ...*model.LogType) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a logHasOneLogTypeTx) Replace(values ...*model.LogType) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a logHasOneLogTypeTx) Delete(values ...*model.LogType) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a logHasOneLogTypeTx) Clear() error {
	return a.tx.Clear()
}

func (a logHasOneLogTypeTx) Count() int64 {
	return a.tx.Count()
}

func (a logHasOneLogTypeTx) Unscoped() *logHasOneLogTypeTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type logDo struct{ gen.DO }

func (l logDo) Debug() *logDo {
	return l.withDO(l.DO.Debug())
}

func (l logDo) WithContext(ctx context.Context) *logDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l logDo) ReadDB() *logDo {
	return l.Clauses(dbresolver.Read)
}

func (l logDo) WriteDB() *logDo {
	return l.Clauses(dbresolver.Write)
}

func (l logDo) Session(config *gorm.Session) *logDo {
	return l.withDO(l.DO.Session(config))
}

func (l logDo) Clauses(conds ...clause.Expression) *logDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l logDo) Returning(value interface{}, columns ...string) *logDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l logDo) Not(conds ...gen.Condition) *logDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l logDo) Or(conds ...gen.Condition) *logDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l logDo) Select(conds ...field.Expr) *logDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l logDo) Where(conds ...gen.Condition) *logDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l logDo) Order(conds ...field.Expr) *logDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l logDo) Distinct(cols ...field.Expr) *logDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l logDo) Omit(cols ...field.Expr) *logDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l logDo) Join(table schema.Tabler, on ...field.Expr) *logDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l logDo) LeftJoin(table schema.Tabler, on ...field.Expr) *logDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l logDo) RightJoin(table schema.Tabler, on ...field.Expr) *logDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l logDo) Group(cols ...field.Expr) *logDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l logDo) Having(conds ...gen.Condition) *logDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l logDo) Limit(limit int) *logDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l logDo) Offset(offset int) *logDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l logDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *logDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l logDo) Unscoped() *logDo {
	return l.withDO(l.DO.Unscoped())
}

func (l logDo) Create(values ...*model.Log) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l logDo) CreateInBatches(values []*model.Log, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l logDo) Save(values ...*model.Log) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l logDo) First() (*model.Log, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Log), nil
	}
}

func (l logDo) Take() (*model.Log, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Log), nil
	}
}

func (l logDo) Last() (*model.Log, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Log), nil
	}
}

func (l logDo) Find() ([]*model.Log, error) {
	result, err := l.DO.Find()
	return result.([]*model.Log), err
}

func (l logDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Log, err error) {
	buf := make([]*model.Log, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l logDo) FindInBatches(result *[]*model.Log, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l logDo) Attrs(attrs ...field.AssignExpr) *logDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l logDo) Assign(attrs ...field.AssignExpr) *logDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l logDo) Joins(fields ...field.RelationField) *logDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l logDo) Preload(fields ...field.RelationField) *logDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l logDo) FirstOrInit() (*model.Log, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Log), nil
	}
}

func (l logDo) FirstOrCreate() (*model.Log, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Log), nil
	}
}

func (l logDo) FindByPage(offset int, limit int) (result []*model.Log, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l logDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l logDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l logDo) Delete(models ...*model.Log) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *logDo) withDO(do gen.Dao) *logDo {
	l.DO = *do.(*gen.DO)
	return l
}
