// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/orm/model"
)

func newMenuAPI(db *gorm.DB, opts ...gen.DOOption) menuAPI {
	_menuAPI := menuAPI{}

	_menuAPI.menuAPIDo.UseDB(db, opts...)
	_menuAPI.menuAPIDo.UseModel(&model.MenuAPI{})

	tableName := _menuAPI.menuAPIDo.TableName()
	_menuAPI.ALL = field.NewAsterisk(tableName)
	_menuAPI.ID = field.NewUint32(tableName, "id")
	_menuAPI.AppID = field.NewUint32(tableName, "app_id")
	_menuAPI.MenuID = field.NewUint32(tableName, "menu_id")
	_menuAPI.Path = field.NewString(tableName, "path")
	_menuAPI.Tag = field.NewString(tableName, "tag")

	_menuAPI.fillFieldMap()

	return _menuAPI
}

// menuAPI 菜单权限接口
type menuAPI struct {
	menuAPIDo

	ALL    field.Asterisk
	ID     field.Uint32
	AppID  field.Uint32 // 应用ID
	MenuID field.Uint32 // 菜单ID
	Path   field.String // API路由地址
	Tag    field.String // 标识

	fieldMap map[string]field.Expr
}

func (m menuAPI) Table(newTableName string) *menuAPI {
	m.menuAPIDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m menuAPI) As(alias string) *menuAPI {
	m.menuAPIDo.DO = *(m.menuAPIDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *menuAPI) updateTableName(table string) *menuAPI {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint32(table, "id")
	m.AppID = field.NewUint32(table, "app_id")
	m.MenuID = field.NewUint32(table, "menu_id")
	m.Path = field.NewString(table, "path")
	m.Tag = field.NewString(table, "tag")

	m.fillFieldMap()

	return m
}

func (m *menuAPI) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *menuAPI) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 5)
	m.fieldMap["id"] = m.ID
	m.fieldMap["app_id"] = m.AppID
	m.fieldMap["menu_id"] = m.MenuID
	m.fieldMap["path"] = m.Path
	m.fieldMap["tag"] = m.Tag
}

func (m menuAPI) clone(db *gorm.DB) menuAPI {
	m.menuAPIDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m menuAPI) replaceDB(db *gorm.DB) menuAPI {
	m.menuAPIDo.ReplaceDB(db)
	return m
}

type menuAPIDo struct{ gen.DO }

func (m menuAPIDo) Debug() *menuAPIDo {
	return m.withDO(m.DO.Debug())
}

func (m menuAPIDo) WithContext(ctx context.Context) *menuAPIDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m menuAPIDo) ReadDB() *menuAPIDo {
	return m.Clauses(dbresolver.Read)
}

func (m menuAPIDo) WriteDB() *menuAPIDo {
	return m.Clauses(dbresolver.Write)
}

func (m menuAPIDo) Session(config *gorm.Session) *menuAPIDo {
	return m.withDO(m.DO.Session(config))
}

func (m menuAPIDo) Clauses(conds ...clause.Expression) *menuAPIDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m menuAPIDo) Returning(value interface{}, columns ...string) *menuAPIDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m menuAPIDo) Not(conds ...gen.Condition) *menuAPIDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m menuAPIDo) Or(conds ...gen.Condition) *menuAPIDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m menuAPIDo) Select(conds ...field.Expr) *menuAPIDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m menuAPIDo) Where(conds ...gen.Condition) *menuAPIDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m menuAPIDo) Order(conds ...field.Expr) *menuAPIDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m menuAPIDo) Distinct(cols ...field.Expr) *menuAPIDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m menuAPIDo) Omit(cols ...field.Expr) *menuAPIDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m menuAPIDo) Join(table schema.Tabler, on ...field.Expr) *menuAPIDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m menuAPIDo) LeftJoin(table schema.Tabler, on ...field.Expr) *menuAPIDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m menuAPIDo) RightJoin(table schema.Tabler, on ...field.Expr) *menuAPIDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m menuAPIDo) Group(cols ...field.Expr) *menuAPIDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m menuAPIDo) Having(conds ...gen.Condition) *menuAPIDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m menuAPIDo) Limit(limit int) *menuAPIDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m menuAPIDo) Offset(offset int) *menuAPIDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m menuAPIDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *menuAPIDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m menuAPIDo) Unscoped() *menuAPIDo {
	return m.withDO(m.DO.Unscoped())
}

func (m menuAPIDo) Create(values ...*model.MenuAPI) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m menuAPIDo) CreateInBatches(values []*model.MenuAPI, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m menuAPIDo) Save(values ...*model.MenuAPI) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m menuAPIDo) First() (*model.MenuAPI, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuAPI), nil
	}
}

func (m menuAPIDo) Take() (*model.MenuAPI, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuAPI), nil
	}
}

func (m menuAPIDo) Last() (*model.MenuAPI, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuAPI), nil
	}
}

func (m menuAPIDo) Find() ([]*model.MenuAPI, error) {
	result, err := m.DO.Find()
	return result.([]*model.MenuAPI), err
}

func (m menuAPIDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MenuAPI, err error) {
	buf := make([]*model.MenuAPI, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m menuAPIDo) FindInBatches(result *[]*model.MenuAPI, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m menuAPIDo) Attrs(attrs ...field.AssignExpr) *menuAPIDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m menuAPIDo) Assign(attrs ...field.AssignExpr) *menuAPIDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m menuAPIDo) Joins(fields ...field.RelationField) *menuAPIDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m menuAPIDo) Preload(fields ...field.RelationField) *menuAPIDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m menuAPIDo) FirstOrInit() (*model.MenuAPI, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuAPI), nil
	}
}

func (m menuAPIDo) FirstOrCreate() (*model.MenuAPI, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MenuAPI), nil
	}
}

func (m menuAPIDo) FindByPage(offset int, limit int) (result []*model.MenuAPI, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m menuAPIDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m menuAPIDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m menuAPIDo) Delete(models ...*model.MenuAPI) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *menuAPIDo) withDO(do gen.Dao) *menuAPIDo {
	m.DO = *do.(*gen.DO)
	return m
}
