
[main]
#数据库类型
type = "mysql"
#数据库地址
host = "ecs.kyour.cn"
#端口
port = 8306
#用户
user = "go-admin"
#密码
pass = "admin123"
#数据库名
database = "go-admin"
#连接参数
param = ""
# 慢日志阈值（毫秒）0为不开启
slow_log_time = 500
